mutation Search($query: String!, $selector: String!) {
  search(query: $query, selector: $selector) {
    items {
      name
      exportStatus
      filePath
      type
      category
      location {
        start {
          line
          column
        }
        end {
          line
          column
        }
      }
      columnValues {
        key
        properties
      }
    }
  }
}
